name: ${project.name}
version: ${project.version}-b${BUILD_NUMBER}

author: aumgn
website: ${project.url}

main: fr.aumgn.dac2.DACPlugin
depend: [WorldEdit]

commands:
    dac2:
        description: "Main command"
        usage: ""
        aliases: ["dac"]

    # Admin Commands
    "dac2 version":
        description: "Show current version."
        usage: ""
        permission: "dac2.admin.version"
    "dac2 reload":
        description: "Reload all data (config, messages, ...)"
        usage: ""
        permission: "dac2.admin.reload"

    # Arenas Commands
    "dac2 define":
        description: "Create an arena with the given name and world."
        usage: "<name> [world]"
        permission: "dac2.arenas.define"
        aliases: ["dac2 def"]
    "dac2 delete":
        description: "Remove given arena."
        usage: "<arena>"
        permission: "dac2.arenas.delete"
        aliases: ["dac2 del", "dac2 remove", "dac2 rm"]
    "dac2 arenas":
        description: "List all arenas."
        usage: ""
        permission: "dac.arenas.arenas"
        aliases: ["dac2 list", "dac2 ls"]
    "dac2 tparena":
        description: "Teleport to the given arena's diving board."
        usage: "<arena>"
        permission: "dac2.arenas.tparena"
    "dac2 select":
        description: "Select specified region of the gievn arena."
        usage: "<pool|start> <arena>"
        permission: "dac2.arenas.select"
        aliases: ["dac2 sel"]

    # Setup Commands
    "dac2 set":
        description: "Set main command"
    "dac2 set pool":
        description: "Define the pool of the given arena."
        usage: "<arena>"
        permission: "dac2.setup.pool"
        aliases: ["dac2 set p"]
    "dac2 set start":
        description: "Define the start region of the given arena."
        usage: "<arena>"
        permission: "dac2.setup.start"
        aliases: ["dac2 set s"]
    "dac2 set diving":
        description: "Define the diving of the given arena."
        usage: "<arena>"
        permission: "dac2.setup.diving"
        aliases: ["dac2 set d"]

permissions:
    "dac2.*":
        default: op
        children:
            - dac2.admin: true
            - dac2.arenas: true
            - dac2.setup: true

    dac2.admin:
        children:
            - dac2.admin.version: true
            - dac2.admin.reload: true

    dac2.arenas:
        children:
            - dac2.arenas.define: true
            - dac2.arenas.delete: true
            - dac2.arenas.arenas: true
            - dac2.arenas.tparena: true
            - dac2.arenas.select: true

    dac2.setup:
        children:
            - dac2.setup.pool: true
            - dac2.setup.start: true
            - dac2.setup.diving: true
