name: ${project.name}
version: ${project.version}-b${BUILD_NUMBER}

author: aumgn
website: ${project.url}

main: fr.aumgn.dac2.DACPlugin
softdepend: [WorldEdit]

commands:
    dac2:
        description: "Main command"
        usage: "<subcommand>"
        aliases: ["dac"]

    # Admin Commands
    "dac2 version":
        description: "Show current version."
        usage: ""
        permission: "dac2.admin.version"
    "dac2 reload":
        description: "Reload all data (config, messages, ...)"
        usage: ""
        permission: "dac2.admin.reload"

    # Arenas Commands
    "dac2 define":
        description: "Create an arena with the given name and world."
        usage: "<name> [world]"
        permission: "dac2.arenas.define"
        aliases: ["dac2 def"]
    "dac2 delete":
        description: "Remove given arena."
        usage: "<arena>"
        permission: "dac2.arenas.delete"
        aliases: ["dac2 del", "dac2 remove", "dac2 rm"]
    "dac2 arenas":
        description: "List all arenas."
        usage: ""
        permission: "dac.arenas.arenas"
        aliases: ["dac2 list", "dac2 ls"]
    "dac2 tparena":
        description: "Teleport to the given arena's diving board."
        usage: "<arena>"
        permission: "dac2.arenas.tparena"
    "dac2 reset":
        description: "Reset the given arena's pool."
        usage: "<arena>"
        permission: "dac2.arenas.reset"
        aliases: ["dac rs"]

    # Setup Commands
    "dac2 set":
        description: "Set main commands"
        usage: "<diving|pool|start|surrounding> <arena>"
    "dac2 set diving":
        description: "Define the diving of the given arena."
        usage: "<arena> [-p=<player>]"
        permission: "dac2.setup.diving"
        aliases: ["dac2 set d"]
    "dac2 set pool":
        description: "Define the pool of the given arena."
        usage: "<arena> [-p=<player>] [-s=shape(default=arbitrary)] [radius] [height]"
        permission: "dac2.setup.pool"
        aliases: ["dac2 set p"]
    "dac2 set start":
        description: "Define the start region of the given arena."
        usage: "<arena> [-p=<player>] [-s=shape(default=cuboid)] [radius] [height]"
        permission: "dac2.setup.start"
        aliases: ["dac2 set s"]

    # WorlEdit Setup Commands
    "dac2 setwe":
        description: "WorldEdit set main command"
        usage: "<pool|start|surrounding> <arena>"
    "dac2 setwe pool":
        description: "Define the pool of the given arena."
        usage: "<arena>"
        permission: "dac2.setup.we.pool"
        aliases: ["dac2 setwe p"]
    "dac2 setwe start":
        description: "Define the start region of the given arena."
        usage: "<arena>"
        permission: "dac2.setup.we.start"
        aliases: ["dac2 setwe s"]
    "dac2 setwe surrounding":
        description: "Define the surrounding region of the given arena."
        usage: "<arena>"
        permission: "dac2.setup.we.surrouding"
        aliases: ["dac2 setwe su"]

    # Select Commands
    "dac2 select":
        description: "Select main command."
        usage: "<pool|start|surrounding> <arena>"
        aliases: ["dac2 sel"]
    "dac2 select pool":
        description: "Select the pool of the given arena."
        usage: "<arena>"
        permission: "dac2.arenas.select.pool"
        aliases: ["dac2 sel p"]
    "dac2 select start":
        description: "Select the start region of the given arena."
        usage: "<arena>"
        permission: "dac2.arenas.select.start"
        aliases: ["dac2 sel s"]
    "dac2 select surrounding":
        description: "Select the surrounding region of the given arena."
        usage: " <arena>"
        permission: "dac2.arenas.select.surrounding"
        aliases: ["dac2 sel su"]

    # Stages Commands
    "dac2 initialize":
        description: "Initialize a new game in the given arena"
        usage: "[arena]"
        permission: "dac2.stages.init"
        aliases: ["dac2 init"]
    "dac2 join":
        description: "Join a game"
        usage: "[-a=<arena>]  [colors...]"
        permission: "dac2.stages.join"
        aliases: ["dac2 j"]
    "dac2 stop":
        description: "Stop a game."
        usage: "[arena]"
        permission: "dac2.stages.stop"
    "dac2 start":
        description: "Start the game."
        usage: "[-a=arena] [gamemode]"
        permission: "dac2.stages.start"
        aliases: ["dac2 s"]
    "dac2 quickstart":
        description: "Start the game skipping the join stage"
        usage: "[-a=arena] [gamemode]"
        permission: "dac2.stages.quickstart"
        aliases: ["dac2 qs"]

permissions:
    "dac2.*":
        default: op
        children:
            - dac2.admin: true
            - dac2.arenas: true
            - dac2.setup: true
            - dac2.select: true
            - dac2.stages: true

    dac2.admin:
        children:
            - dac2.admin.version: true
            - dac2.admin.reload: true

    dac2.arenas:
        children:
            - dac2.arenas.define: true
            - dac2.arenas.delete: true
            - dac2.arenas.arenas: true
            - dac2.arenas.tparena: true
            - dac2.arenas.reset: true

    dac2.setup:
        children:
            - dac2.setup.diving: true
            - dac2.setup.pool: true
            - dac2.setup.start: true
            - dac2.setup.we: true

    dac2.setup.we:
        children:
            - dac2.setup.we.pool: true
            - dac2.setup.we.start: true
            - dac2.setup.we.surrouding: true

    dac2.select:
        children:
            - dac2.arenas.select.pool: true
            - dac2.arenas.select.start: true
            - dac2.arenas.select.surrounding: true

    dac2.stages:
        children:
            - dac2.stages.init: true
            - dac2.stages.init.arena: true
            - dac2.stages.join: true
            - dac2.stages.join.arena: true
            - dac2.stages.stop: true
            - dac2.stages.stop.others: true
            - dac2.stages.start: true
            - dac2.stages.start.others: true
            - dac2.stages.quickstart: true
            - dac2.stages.quickstart.arena: true
