name: ${project.name}
version: ${project.version}
author: aumgn
website: aumgn.fr

main: fr.aumgn.dac.DACPlugin
depend: [WorldEdit]

commands:
    dac:
        usage: "Utilisation: /<command> join | start | stop | reset | quit | lives | goto"
    dac-reload:
        description: 'Recharge la configuration du plugin.'
        usage: "Utilisation: /<command>"
        permission: 'dac.cmd.reload'
    dac-define:
        description: 'Defini une nouvelle arene de jeu dans le monde actuel.'
        usage: "Utilisation: /<command> <arene>"
        permission: 'dac.cmd.define'
        aliases: ["dac-def"]
    dac-delete:
        description: 'Supprime une arene'
        usage: "Utilisation: /<command> <arene>"
        permission: 'dac.cmd.delete'
        aliases: ["dac-remove", "dac-del", "dac-rm"]
    dac-arenas:
        description: 'Liste les arenes'
        usage: '/<command>'
        permission: 'dac.cmd.arenas'
    dac-set:
        description: 'Assigne une zone ou un emplacement.'
        usage: 'Utilisation: /<command> <arene> pool|start|diving'
        permission: 'dac.cmd.set'
    dac-select:
        description: 'Charge la zone en tant que selection WorldEdit.'
        usage: 'Utilisation: /<command> <arene> pool|start'
        permission: 'dac.cmd.select'
        aliases: ["dac-sel"]
    dac-stop:
        description: 'Arrete la partie en cours si partie il y a.'
        usage: 'Utilisation: /<command>'
        permission: 'dac.cmd.stop'
    dac-kick:
        description: 'Kick un joueur.'
        usage: 'Utilisation: /<command> player'
        permission: 'dac.cmd.kick'
    dac-reset:
        description: "Remplis le bassin d'eau"
        usage: 'Utilisation: /<command> <arene>'
        permission: 'dac.cmd.reset'
        aliases: ["dac-r"]
    dac-join:
        description: "Permets de rejoindre une nouvelle partie ou d'en creer une nouvelle."
        usage: 'Utilisation: /<command> [<color> [<color2> [...]]]'
        permission: 'dac.cmd.join'
        aliases: ["dac-j"]
    dac-start: 
        description: 'Debute une nouvelle partie avec les joueurs presents dans la zone de depart.'
        usage: 'Utilisation: /<command>'
        permission: 'dac.cmd.start'
        aliases: ["dac-s"]
    dac-quit:
        description: "Quitter la partie en cours"
        usage: 'Utilisation: /<command>'
        permission: 'dac.cmd.quit'
        aliases: ["dac-q"]
    dac-list:
        description: 'Affiche le nombre de vies du joueur selectionne ou de tous les joueurs'
        usage: 'Utilisation: /<command> [<joueur>]'
        permission: 'dac.cmd.lives'
        aliases: ["dac-players", "dac-lives"]
    dac-goto:
        description: 'Teleporte le joueur sur le plongeoir ou a sa position de depart'
        usage: 'Utilisation: /<command> diving|start'
        permission: 'dac.cmd.goto'
        aliases: ["dac-teleport", "dac-g", "dac-tp"]
    dac-colors:
        description: "Liste l'ensemble des couleurs disponibles"
        usage: 'Utilisation: /<command>'
        permission: 'dac.cmd.colors'
        
permissions:
    dac.game.play:
        description: 'Permets de jouer.'
        default: true
        children:
            dac.cmd.join: true
            dac.cmd.start: true
            dac.cmd.reset: true
            dac.cmd.quit: true
            dac.cmd.lives: true
            dac.cmd.goto: true
            dac.cmd.colors: true
    dac.game.reset:
        description: "Permets de remettre a zéro le bassin in-game"
        default: op
    dac.game.manage:
        description: "Permets de gerer le deroulement d'une partie et de jouer."
        default: op
        children:
            dac.game.play : true
            dac.game.reset: true
            dac.cmd.kick: true
            dac.cmd.stop: true
    dac.config:
        description: "Permets de mettre en place les zones du jeu."
        default: op
        children:
            dac.cmd.reload: true
            dac.cmd.define: true
            dac.cmd.delete: true
            dac.cmd.arenas: true
            dac.cmd.set: true
            dac.cmd.select: true            

